/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.portaria.view;

import com.portaria.session.SessionManager;
import java.awt.EventQueue;
import javax.swing.JFrame;

/**
 *
 * @author visitante
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        entradaMenu = new javax.swing.JMenu();
        saidaMenu = new javax.swing.JMenu();
        manutencaoMenu = new javax.swing.JMenu();
        pessoaMenuManutencaoItem = new javax.swing.JMenuItem();
        veiculoMenuManutencaoItem = new javax.swing.JMenuItem();
        usuarioMenuManutencaoItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        entradaMenu.setText("Entrada");
        entradaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entradaMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(entradaMenu);

        saidaMenu.setText("Saída");
        jMenuBar1.add(saidaMenu);

        manutencaoMenu.setText("Manutenção");

        pessoaMenuManutencaoItem.setText("Pessoa");
        pessoaMenuManutencaoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaMenuManutencaoItemActionPerformed(evt);
            }
        });
        manutencaoMenu.add(pessoaMenuManutencaoItem);

        veiculoMenuManutencaoItem.setText("Veículo");
        veiculoMenuManutencaoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoMenuManutencaoItemActionPerformed(evt);
            }
        });
        manutencaoMenu.add(veiculoMenuManutencaoItem);

        usuarioMenuManutencaoItem.setText("Usuário");
        usuarioMenuManutencaoItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioMenuManutencaoItemMouseClicked(evt);
            }
        });
        usuarioMenuManutencaoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioMenuManutencaoItemActionPerformed(evt);
            }
        });
        manutencaoMenu.add(usuarioMenuManutencaoItem);

        jMenuBar1.add(manutencaoMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void veiculoMenuManutencaoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoMenuManutencaoItemActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new ManutencaoVeiculoView().setVisible(true);
        });
    }//GEN-LAST:event_veiculoMenuManutencaoItemActionPerformed

    private void pessoaMenuManutencaoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaMenuManutencaoItemActionPerformed
        EventQueue.invokeLater(() -> {
            JFrame frame = new JFrame();
            frame.setContentPane(new ManutencaoPessoaView());
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.pack();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        });
    }//GEN-LAST:event_pessoaMenuManutencaoItemActionPerformed

    private void usuarioMenuManutencaoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioMenuManutencaoItemActionPerformed
        EventQueue.invokeLater(() -> {
            JFrame frame = new JFrame();
            frame.setContentPane(new ManutencaoUsuarioView());
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.pack();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        });
    }//GEN-LAST:event_usuarioMenuManutencaoItemActionPerformed

    private void usuarioMenuManutencaoItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioMenuManutencaoItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioMenuManutencaoItemMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (SessionManager.getUsuarioLogado() == null) {
            new Thread(() -> {
                new LoginView(this, true).setVisible(true);
            }).start();
        }
    }//GEN-LAST:event_formWindowOpened

    private void entradaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradaMenuMouseClicked
        EventQueue.invokeLater(() -> {
            JFrame frame = new JFrame();
            frame.setContentPane(new ManutencaoEntradasView());
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.pack();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        });
    }//GEN-LAST:event_entradaMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PrincipalView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu entradaMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu manutencaoMenu;
    private javax.swing.JMenuItem pessoaMenuManutencaoItem;
    private javax.swing.JMenu saidaMenu;
    private javax.swing.JMenuItem usuarioMenuManutencaoItem;
    private javax.swing.JMenuItem veiculoMenuManutencaoItem;
    // End of variables declaration//GEN-END:variables
}
